service: __PROJECT_SLUG__-layer-domain

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, '__AWS_REGION__'}

layers:
  domain:
    path: nodejs
    name: ${self:service}-${sls:stage}
    description: Shared domain helpers used by multiple APIs.
